version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./wp-content/themes:/app/wp-content/themes   # Yours Theme
      - ./wp-content/plugins:/app/wp-content/plugins   # Yours Plugins
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        better-wp-security,
        disable-json-api,
        force-email-login,
        wp-db-backup
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./.data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    links:
      - db
    ports:
     - 8000:80
    volumes:
     - /sessions